const { withAndroidStyles } = require('@expo/config-plugins');

// Under edge-to-edge layout (mandatory on Android in Expo SDK 54+) the navigation
// bar is transparent and the app draws behind it, but Android paints a translucent
// grey "contrast" scrim behind the bar by default. The app hides the nav bar at
// startup (App.tsx), yet focusing a TextInput forces it back and the scrim can show
// as a grey band. Disabling enforceNavigationBarContrast lets the app's own
// background show through instead.
//
// android/ is generated by prebuild, so this AppTheme override lives in a config
// plugin rather than a hand-edited styles.xml.
const ITEM_NAME = 'android:enforceNavigationBarContrast';

const withNavigationBarContrast = (config) =>
  withAndroidStyles(config, (config) => {
    const styles = config.modResults.resources.style ?? [];
    const appTheme = styles.find((s) => s.$ && s.$.name === 'AppTheme');
    if (appTheme) {
      appTheme.item = (appTheme.item ?? []).filter((i) => !(i.$ && i.$.name === ITEM_NAME));
      appTheme.item.push({ $: { name: ITEM_NAME }, _: 'false' });
    }
    return config;
  });

module.exports = withNavigationBarContrast;
