-- ============================================================
-- devices
-- One row per registered app installation.
-- UUID is generated by the app on first launch (stable identity).
-- FCM token is updated via onTokenRefresh when Firebase rotates it.
-- fcm_token is UNIQUE: a token identifies exactly one app install / delivery target,
--   so two rows can never share one. This is the structural backstop that, together with
--   the register_device RPC below, stops one device from accumulating duplicate rows
--   across reinstalls (each of which would otherwise receive a duplicate push).
-- notify_at: null = receive notification at cron time (MVP default).
--   V2: cron runs hourly and only notifies devices whose notify_at matches.
-- ============================================================
CREATE TABLE IF NOT EXISTS devices (
  id         UUID        PRIMARY KEY,
  fcm_token  TEXT        NOT NULL,
  notify_at  TIME,
  user_id    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Uniqueness backstop as a standalone constraint, not an inline column UNIQUE: with
-- CREATE TABLE IF NOT EXISTS above, an inline constraint would be silently skipped when
-- this file is re-applied to an already-existing devices table, leaving duplicate-token
-- rows possible. The ALTER applies the constraint regardless of whether the table is new.
ALTER TABLE devices ADD CONSTRAINT devices_fcm_token_key UNIQUE (fcm_token);

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;

-- All client writes go through SECURITY DEFINER RPCs (register_device,
-- update_notify_time, link_device_to_user); the cron reads via the service-role
-- key, which bypasses RLS. No open policy is defined, so RLS denies every direct
-- anon/authenticated SELECT/INSERT/UPDATE — closing publishable-key token
-- harvesting and blind tampering. DROP IF EXISTS keeps re-applying this file
-- idempotent against a database that still carries the old open policies.
DROP POLICY IF EXISTS "device self-select"   ON devices;
DROP POLICY IF EXISTS "device self-register" ON devices;
DROP POLICY IF EXISTS "device self-update"   ON devices;

-- register_device — the canonical device-registration write path (app + cron both call it).
-- Keeps `id` (stable per install) as the upsert conflict target — correct for the frequent
-- case of an FCM token rotating on an existing install. Additionally evicts any *other* row
-- that already holds the incoming token, which collapses the rare reinstall case (the
-- per-install id is regenerated while Play Services hands back the surviving token) down to a
-- single row. Runs as SECURITY DEFINER so it can DELETE the prior owner — the app's
-- publishable key has no DELETE policy on `devices`.
CREATE OR REPLACE FUNCTION register_device(
  p_id      uuid,
  p_token   text,
  p_user_id uuid DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Reinstall ghost / FCM token reassignment: a different row currently owns this token.
  -- Evict it so the upsert below can take the token over without violating UNIQUE(fcm_token).
  DELETE FROM devices WHERE fcm_token = p_token AND id <> p_id;

  -- Upsert by the stable per-install id. Only overwrite user_id when provided, so a pre-auth
  -- re-register (p_user_id = NULL) never clobbers an existing link. notify_at is intentionally
  -- untouched — it is owned by the app's updateNotifyTime, and registration must preserve it.
  INSERT INTO devices (id, fcm_token, user_id, updated_at)
  VALUES (p_id, p_token, p_user_id, now())
  ON CONFLICT (id) DO UPDATE SET
    fcm_token  = EXCLUDED.fcm_token,
    user_id    = COALESCE(EXCLUDED.user_id, devices.user_id),
    updated_at = now();
END;
$$;

GRANT EXECUTE ON FUNCTION register_device(uuid, text, uuid) TO anon, authenticated, service_role;

-- update_notify_time — the only path for the app to change a device's notify_at.
-- Definer so it works with the publishable key against the now-policyless table.
-- Keyed by the per-install device UUID (an unguessable capability). Returns FOUND
-- so the app can warn when the row does not exist yet (registration not finished).
CREATE OR REPLACE FUNCTION update_notify_time(p_id uuid, p_notify_at time)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE devices
    SET notify_at = p_notify_at, updated_at = now()
    WHERE id = p_id;
  RETURN FOUND;
END;
$$;

REVOKE EXECUTE ON FUNCTION update_notify_time(uuid, time) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION update_notify_time(uuid, time) TO anon, authenticated, service_role;

-- link_device_to_user — stamps the auth link onto a device row. user_id is NOT a
-- parameter: it is derived from the caller's JWT via auth.uid(), so a device can
-- only ever be linked to the authenticated caller's own identity. Granted to
-- authenticated only (the app calls this exclusively post-login). Returns FOUND so
-- the app's retry can wait for the row to appear.
CREATE OR REPLACE FUNCTION link_device_to_user(p_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'link_device_to_user requires an authenticated user';
  END IF;
  UPDATE devices
    SET user_id = v_uid, updated_at = now()
    WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- Revoke anon explicitly, not just PUBLIC: Supabase's ALTER DEFAULT PRIVILEGES
-- auto-grants EXECUTE on every new public function directly to anon (as well as
-- authenticated/service_role), so REVOKE FROM PUBLIC alone would leave anon able to
-- call this. Same reason peek/claim revoke from anon above. authenticated keeps it.
REVOKE EXECUTE ON FUNCTION link_device_to_user(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION link_device_to_user(uuid) TO authenticated, service_role;


-- ============================================================
-- user_preferences
-- One row per authenticated user, written/read via RLS (auth.uid() = user_id).
-- ============================================================
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id     UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  preferences JSONB       NOT NULL DEFAULT '{}',
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user read own prefs"
  ON user_preferences FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "user write own prefs"
  ON user_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user update own prefs"
  ON user_preferences FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- digests
-- One row per region per date, shared across all users.
-- Cron writes once daily; app reads for its selected regions.
-- Eviction: cron deletes rows older than 7 days before writing.
-- PRIMARY KEY (region, date) already covers the main app query:
--   WHERE region = ANY($1) AND date = $2
-- No extra index needed — max ~56 rows (8 regions × 7 days).
-- ============================================================
CREATE TABLE IF NOT EXISTS digests (
  region      TEXT        NOT NULL,
  date        DATE        NOT NULL,
  payload     JSONB       NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (region, date)
);

ALTER TABLE digests ENABLE ROW LEVEL SECURITY;

-- Required: RLS default denies everything. This allows the app's
-- publishable key to SELECT. Secret key bypasses RLS — no write policy needed.
CREATE POLICY "public read"
  ON digests
  FOR SELECT
  USING (true);

-- ============================================================
-- notify_state
-- Single-row store of the last time jobs/notify.ts processed a window.
-- jobs/notify.ts notifies devices whose notify_at fell in (last_run_at, now],
-- so no device is dropped when the GitHub Actions schedule fires irregularly.
-- Seeded with now() so the first run after deploy sees a tiny window and does
-- NOT mass-notify every device. Only the cron service-role key touches this
-- table; the service role bypasses RLS, so no policy is defined.
-- ============================================================
CREATE TABLE IF NOT EXISTS notify_state (
  id          BOOLEAN     PRIMARY KEY DEFAULT TRUE CHECK (id),
  last_run_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Exactly one row (id = TRUE); CHECK (id) + the PK forbid a second row.
INSERT INTO notify_state (id) VALUES (TRUE) ON CONFLICT (id) DO NOTHING;

ALTER TABLE notify_state ENABLE ROW LEVEL SECURITY;

-- peek_due_notifications — read-only "is any device due since last_run_at?".
-- Called by the .github/workflows/notify.yml guard step to skip checkout+npm on
-- empty windows. A device is due iff the most recent occurrence of its notify_at
-- (today if it has already passed in UTC, else yesterday) is later than
-- last_run_at. notify_at is a UTC time-of-day, matching the rest of the cron.
CREATE OR REPLACE FUNCTION peek_due_notifications()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM devices d, notify_state s
    WHERE d.notify_at IS NOT NULL
      AND (
        (CASE
           WHEN d.notify_at <= (now() AT TIME ZONE 'UTC')::time
             THEN (now() AT TIME ZONE 'UTC')::date + d.notify_at
             ELSE (now() AT TIME ZONE 'UTC')::date - 1 + d.notify_at
         END) AT TIME ZONE 'UTC'
      ) > s.last_run_at
  );
$$;

-- Service-only: the cron runs as service_role. Postgres + Supabase grant EXECUTE
-- to PUBLIC/anon/authenticated by default, which would let the app's publishable
-- key call this RPC; revoke that so only the secret key can.
REVOKE EXECUTE ON FUNCTION peek_due_notifications() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION peek_due_notifications() TO service_role;

-- claim_due_notifications — returns the FCM tokens of all due devices AND
-- advances last_run_at to now() atomically (FOR UPDATE serialises with the
-- workflow's concurrency group). Advancing before dispatch gives at-most-once
-- delivery, which is preferred over double-notify spam. Called by jobs/notify.ts.
CREATE OR REPLACE FUNCTION claim_due_notifications()
RETURNS TABLE (fcm_token text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now  timestamptz := now();
  v_last timestamptz;
BEGIN
  SELECT s.last_run_at INTO v_last
  FROM notify_state s
  WHERE s.id
  FOR UPDATE;

  RETURN QUERY
    SELECT d.fcm_token
    FROM devices d
    WHERE d.notify_at IS NOT NULL
      AND (
        (CASE
           WHEN d.notify_at <= (v_now AT TIME ZONE 'UTC')::time
             THEN (v_now AT TIME ZONE 'UTC')::date + d.notify_at
             ELSE (v_now AT TIME ZONE 'UTC')::date - 1 + d.notify_at
         END) AT TIME ZONE 'UTC'
      ) > v_last;

  UPDATE notify_state SET last_run_at = v_now WHERE id;
END;
$$;

-- Service-only: claim returns FCM tokens and advances last_run_at, so it must
-- never be reachable with the public anon key. Revoke the default PUBLIC grant.
REVOKE EXECUTE ON FUNCTION claim_due_notifications() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION claim_due_notifications() TO service_role;
